apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: example-runner
  namespace: default
spec:
  repository: zoetrope/vcluster-runner-test
  image: ghcr.io/zoetrope/actions-runner:v0.1.0
  env: []
