apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: example-runner
  namespace: default
spec:
  repository: zoetrope/vcluster-runner-test
  image: ghcr.io/zoetrope/actions-runner:v0.2.0
  env:
    - name: KUBECONFIG
      value: "/etc/kubernetes/config"
  volumeMounts:
    - mountPath: /etc/kubernetes
      name: kubeconfig
      readOnly: true
  volumes:
    - name: kubeconfig
      secret:
        defaultMode: 420
        secretName: vc-test-cluster
