name: CI
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  test:
    name: test
    runs-on: [ self-hosted, linux ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Pod
        run: |
          kubectl --kubeconfig=/etc/kubernetes/config apply -f ./pod.yaml
          kubectl --kubeconfig=/etc/kubernetes/config wait --for=condition=ready pod sample
